"""User-facing texts in German and English (config: allgemein.sprache = "de" | "en").

Nutzertexte auf Deutsch und Englisch. Jeder Schlüssel hat beide Sprachen mit denselben Platzhaltern
(geprüft in tests/test_sprache.py). Interne Bezeichner im Code bleiben deutsch.
"""

AKTUELL = "en"
NUTZER = ""          # optionaler Name des Nutzers für Hook-Texte


def setzen(sprache, name=""):
    global AKTUELL, NUTZER
    AKTUELL = sprache if sprache in ("de", "en") else "en"
    NUTZER = name or ""


def t(schluessel, **werte):
    eintrag = TEXTE[schluessel]
    return (eintrag.get(AKTUELL) or eintrag["en"]).format(**werte)


def prozent(wert):
    return f"{wert:.0f} %" if AKTUELL == "de" else f"{wert:.0f}%"


def wer():
    return NUTZER or t("wer_nutzer")


WOCHENTAGE = {"de": ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
              "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]}

TEXTE = {
    # ------------------------------------------------------------ allgemein
    "app": {"de": "Limit-Wächter", "en": "Limit Watchdog"},
    "art_fuenf": {"de": "5h", "en": "5h"},
    "art_woche": {"de": "Woche", "en": "week"},
    "stand": {"de": "{art} {pct}, Reset {reset}", "en": "{art} {pct}, resets {reset}"},
    "wer_nutzer": {"de": "der Nutzer", "en": "the user"},
    "tage": {"de": "Tagen", "en": "days"},

    # ------------------------------------------------------------ Texte an die Agenten
    "prompt_fortsetzen": {
        "de": "Limit-Wächter: Das Nutzungslimit ist zurückgesetzt. Lies deine letzte Sicherung "
              "(Status-/Übergabedatei, letzte Nachricht, `git log -1`), prüfe den Stand und setze nur Offenes fort. "
              "Abgeschlossene Schritte nicht wiederholen. Ein unterbrochener Dynamic Workflow wird per "
              "`resumeFromRunId` fortgesetzt.",
        "en": "Limit Watchdog: The usage limit has reset. Read your last checkpoint (status/handoff file, "
              "last message, `git log -1`), check the current state and continue only what is still open. "
              "Do not repeat completed steps. Resume an interrupted Dynamic Workflow with `resumeFromRunId`.",
    },
    "hook_herkunft_name": {"de": "eigener Hook von {name}", "en": "hook installed by {name}"},
    "hook_herkunft": {"de": "eigener Hook des Nutzers", "en": "the user's own hook"},
    "sicherung_kopf": {
        "de": "{app} ({herkunft}): Das Claude-Nutzungslimit ist fast erreicht ({stand}). ",
        "en": "{app} ({herkunft}): The Claude usage limit is almost reached ({stand}). ",
    },
    "sicherung_kern": {
        "de": "Bitte jetzt geordnet anhalten: den aktuellen Schritt abschließen, keine neuen Subagents oder "
              "Workflows starten, die vorhandene Status- oder Übergabedatei des Projekts aktualisieren (fertig, "
              "offen, nächster Schritt; keine neue Datei auf Vorrat), bei einem Git-Repo einen WIP-Commit nur der "
              "eigenen Änderungen machen (ohne Push), laufende Dynamic Workflows mit Run-ID notieren und dann den "
              "Turn mit einer kurzen Zusammenfassung beenden.",
        "en": "Please stop in an orderly way now: finish the current step, do not start new subagents or "
              "workflows, update the project's existing status or handoff file (done, open, next step; no new "
              "file just in case), if this is a git repository make a WIP commit of your own changes only "
              "(no push), note the run ID of any running Dynamic Workflow, and then end the turn with a short "
              "summary.",
    },
    "codex_kopf": {
        "de": "{app}: Das Codex-Nutzungslimit ist fast erreicht ({stand}). ",
        "en": "{app}: The Codex usage limit is almost reached ({stand}). ",
    },
    "codex_kern": {
        "de": "Bitte jetzt geordnet anhalten: den aktuellen Schritt abschließen, keine neuen Subagents starten, "
              "die vorhandene Status- oder Übergabedatei des Projekts aktualisieren (fertig, offen, nächster "
              "Schritt; keine neue Datei auf Vorrat), bei einem Git-Repo einen WIP-Commit nur der eigenen "
              "Änderungen machen (ohne Push) und dann mit einer kurzen Zusammenfassung anhalten.",
        "en": "Please stop in an orderly way now: finish the current step, do not start new subagents, update "
              "the project's existing status or handoff file (done, open, next step; no new file just in case), "
              "if this is a git repository make a WIP commit of your own changes only (no push), and then stop "
              "with a short summary.",
    },
    "nach_reset": {"de": " Nach dem Reset setzt der Limit-Wächter automatisch fort.",
                   "en": " After the reset, Limit Watchdog will continue automatically."},
    "ohne_fortsetzung": {
        "de": " Wegen der Wochenreserve gibt es danach keine automatische Fortsetzung; {wer} setzt selbst fort.",
        "en": " Because the weekly reserve is reached there is no automatic continuation afterwards; {wer} will "
              "continue manually.",
    },
    "stopp_kontext": {
        "de": "{app}: Das Claude-Nutzungslimit ist fast erreicht ({stand}). Stopp-Phase: den aktuellen Schritt "
              "abschließen, keine neuen Subagents oder Workflows starten, den Stand sichern und den Turn danach "
              "beenden.",
        "en": "{app}: The Claude usage limit is almost reached ({stand}). Stop phase: finish the current step, "
              "do not start new subagents or workflows, save your progress and then end the turn.",
    },
    "deny_grund": {
        "de": "{app}: Nutzungslimit fast erreicht ({stand}). Bis zum Reset starten keine neuen Subagents oder "
              "Workflows. Bitte den aktuellen Schritt ohne sie abschließen und den Stand sichern.",
        "en": "{app}: Usage limit almost reached ({stand}). No new subagents or workflows until the reset. "
              "Please finish the current step without them and save your progress.",
    },
    "prompt_hinweis": {
        "de": "Hinweis {app}: Nutzungslimit {stand}. Neue Subagents und Workflows sind bis zum Reset gesperrt.",
        "en": "Note from {app}: usage limit {stand}. New subagents and workflows are blocked until the reset.",
    },
    "reserve_block": {
        "de": "{app}: Wochenreserve erreicht (Woche {pctw}). Die automatische Fortsetzung ist gesperrt; {wer} "
              "setzt selbst fort.",
        "en": "{app}: Weekly reserve reached (week {pctw}). Automatic continuation is blocked; {wer} will "
              "continue manually.",
    },
    "terminal_titel": {"de": "{app}: Fortsetzung", "en": "{app}: continuation"},

    # ------------------------------------------------------------ Pushes (kurz, ohne Projektinhalte)
    "push_warnung": {"de": "{n}: {art} bei {pct} (Warnschwelle). Reset {reset}.",
                     "en": "{n}: {art} at {pct} (warning threshold). Resets {reset}."},
    "push_stopp": {
        "de": "{n}: Stopp-Schwelle erreicht ({art} {pct}). Laufende Agenten sichern und halten an. "
              "Reset {reset}.{hinweis}",
        "en": "{n}: stop threshold reached ({art} {pct}). Running agents save their work and pause. "
              "Resets {reset}.{hinweis}",
    },
    "push_limit": {"de": "{n}: Limit erreicht ({art}). Reset {reset}.{warten}{hinweis}",
                   "en": "{n}: limit reached ({art}). Resets {reset}.{warten}{hinweis}"},
    "push_limit_warten": {"de": " {anzahl} Sitzung(en) warten auf Fortsetzung.",
                          "en": " {anzahl} session(s) waiting to continue."},
    "hinweis_kein_netzteil": {"de": " Hinweis: kein Netzteil.", "en": " Note: not on power."},
    "hinweis_remote_aus": {"de": " Hinweis: Remote-Modus aus (zugeklappt schläft der Mac).",
                           "en": " Note: the Mac will sleep if the lid is closed."},
    "nacht_kein_netzteil": {"de": "kein Netzteil.", "en": "not on power."},
    "nacht_remote_aus": {"de": "Remote-Modus aus (zugeklappt schläft der Mac).",
                         "en": "the Mac will sleep if the lid is closed."},
    "nacht_aktion_befehl": {"de": "{befehl} ausführen und das Netzteil anschließen",
                            "en": "run {befehl} and connect power"},
    "nacht_aktion": {"de": "den Mac wach halten (auch zugeklappt, z. B. mit Amphetamine) und ans Netzteil",
                     "en": "keep the Mac awake (also with the lid closed, e.g. with Amphetamine) and on power"},
    "push_remote_nacht": {"de": "Mac: {hinweis} Für die Fortsetzung um {zeit} bitte {aktion}.",
                          "en": "Mac: {hinweis} For the continuation at {zeit}, please {aktion}."},
    "push_reserve": {"de": "{n}: Wochenreserve erreicht (Woche {pctw}). Keine automatische Fortsetzung bis {reset}.",
                     "en": "{n}: weekly reserve reached (week {pctw}). No automatic continuation until {reset}."},
    "push_reset": {"de": "{n}: Limit zurückgesetzt.", "en": "{n}: limit has reset."},
    "push_credits": {"de": "Codex: Guthaben gesunken ({alt} → {neu}). Bitte prüfen.",
                     "en": "Codex: credit balance dropped ({alt} → {neu}). Please check."},
    "push_reset_credits": {
        "de": "Codex: Reset-Credits weniger geworden ({alt} → {neu}). Der Wächter nutzt sie nie – bitte prüfen.",
        "en": "Codex: fewer rate-limit reset credits ({alt} → {neu}). Limit Watchdog never uses them – please check.",
    },
    "push_ueberziehung": {"de": "Claude: Extra-Usage (Credits) war beim Limit aktiv! Bitte prüfen.",
                          "en": "Claude: extra usage (credits) was active at the limit! Please check."},
    "push_freigabe": {"de": "{n}: fortgesetzte Sitzung wartet auf eine Freigabe.",
                      "en": "{n}: a continued session is waiting for a permission prompt."},
    "push_orca_weg": {"de": "Orca nicht erreichbar – Fortsetzung nicht möglich. Bitte Orca öffnen.",
                      "en": "Orca is not reachable – cannot continue sessions. Please open Orca."},
    "push_fortgesetzt": {"de": "{n}: {anzahl} Sitzung(en) fortgesetzt.", "en": "{n}: {anzahl} session(s) continued."},
    "push_morgenbericht": {"de": "Morgenbericht: {kurz}. Details: waechter.py report",
                           "en": "Morning report: {kurz}. Details: waechter.py report"},
    "push_reserve_halt": {
        "de": "{n}: Wochenreserve erreicht – keine automatische Fortsetzung. Bitte selbst fortsetzen.",
        "en": "{n}: weekly reserve reached – no automatic continuation. Please continue manually.",
    },
    "push_aufgegeben": {"de": "{n}: Fortsetzung {max}× versucht – ich höre auf. Bitte selbst ansehen.",
                        "en": "{n}: tried to continue {max}× – giving up. Please take a look."},
    "blockiert_menue": {"de": "am Bildschirm steht ein Menü oder eine Abfrage", "en": "a menu or prompt is on screen"},
    "blockiert_geld": {"de": "am Bildschirm steht ein Kauf- oder Kostenhinweis",
                       "en": "a purchase or billing option is on screen"},
    "blockiert_belegt": {"de": "in der Eingabezeile steht schon Text", "en": "the input line already contains text"},
    "blockiert_unklar": {"de": "der Bildschirm ist unklar", "en": "the screen is unclear"},
    "push_blockiert": {"de": "{n}: Fortsetzung angehalten – {text}. Nichts gesendet, bitte selbst ansehen.",
                       "en": "{n}: continuation paused – {text}. Nothing was sent, please take a look."},
    "push_verloren": {"de": "{n}: fortgesetzte Sitzung nicht wiedergefunden – bitte selbst ansehen.",
                      "en": "{n}: could not find the continued session again – please take a look."},
    "push_haengt": {"de": "{n}: fortgesetzte Sitzung wartet auf eine Eingabe – bitte ansehen.",
                    "en": "{n}: a continued session is waiting for input – please take a look."},
    "push_tickfehler": {"de": "{app}: Fehler im Tick – bitte waechter.py status und das Log ansehen.",
                        "en": "{app}: error during a tick – please check waechter.py status and the log."},
    "push_test": {"de": "Test: Der Limit-Wächter kann dich erreichen.", "en": "Test: Limit Watchdog can reach you."},

    # ------------------------------------------------------------ Aktionen und Log
    "aktion_bericht": {"de": "Morgenbericht gespeichert: {datei}", "en": "Morning report saved: {datei}"},
    "aktion_blockiert": {"de": "BLOCKIERT {s}: {grund}", "en": "BLOCKED {s}: {grund}"},
    "aktion_laeuft": {"de": "LÄUFT BEREITS {s}", "en": "ALREADY RUNNING {s}"},
    "aktion_warte": {"de": "WARTE {s}: Claudes eingebautes Warten ist noch aktiv",
                     "en": "WAITING {s}: Claude's built-in wait is still active"},
    "aktion_fortgesetzt": {"de": "FORTGESETZT {s} per {weg}", "en": "CONTINUED {s} via {weg}"},
    "aktion_neu": {"de": "NEU GESTARTET {s} in {sel}", "en": "RESTARTED {s} in {sel}"},
    "aktion_codex_limit": {"de": "CODEX-LIMIT {id} Reset {zeit}", "en": "CODEX LIMIT {id} resets {zeit}"},
    "aktion_codex_stopp": {"de": "CODEX-STOPP {id} ({projekt}): {ergebnis}", "en": "CODEX STOP {id} ({projekt}): {ergebnis}"},
    "angenommen": {"de": "angenommen", "en": "accepted"},
    "nicht_angenommen": {"de": "NICHT angenommen", "en": "NOT accepted"},
    "weg_enter": {"de": "Enter (nach Schlaf)", "en": "Enter (after sleep)"},
    "weg_prompt": {"de": "Fortsetzungsprompt", "en": "continuation prompt"},
    "weg_neu": {"de": "neues Terminal", "en": "new terminal"},
    "grund_bild": {"de": "Bildschirm nicht lesbar: {fehler}", "en": "screen not readable: {fehler}"},
    "grund_senden": {"de": "Senden nicht bestätigt: {fehler}", "en": "sending not confirmed: {fehler}"},
    "grund_nicht_angenommen": {"de": "nicht angenommen", "en": "not accepted"},
    "grund_ordner": {"de": "Terminal fehlt und Projektordner unbekannt",
                     "en": "terminal missing and project folder unknown"},
    "grund_agents": {"de": "Terminal fehlt; `claude agents` nicht lesbar – kein Neustart auf Verdacht",
                     "en": "terminal missing; `claude agents` not readable – no blind restart"},
    "grund_woanders": {"de": "Sitzung läuft außerhalb eines Orca-Terminals – keine Kopie starten",
                       "en": "session is running outside an Orca terminal – not starting a copy"},
    "grund_erstellen": {"de": "Terminal konnte nicht erstellt werden: {fehler}",
                        "en": "could not create a terminal: {fehler}"},
    "log_bildschirm": {"de": "Bildschirm {s}: {art} ({grund}) :: {ausschnitt}",
                       "en": "Screen {s}: {art} ({grund}) :: {ausschnitt}"},
    "log_pruefung": {"de": "Prüfung {s}: {art} :: {ausschnitt}", "en": "Check {s}: {art} :: {ausschnitt}"},
    "log_weitere": {"de": "{anzahl} weitere Fortsetzung(en) im nächsten Tick",
                    "en": "{anzahl} more continuation(s) in the next tick"},
    "log_pausiert": {"de": " (pausiert)", "en": " (paused)"},
    "log_phase": {"de": "PHASE {anb}: {alt} -> {neu} ({stand})", "en": "PHASE {anb}: {alt} -> {neu} ({stand})"},
    "log_codex_kein_thread": {"de": "Codex-Terminal {handle}: kein Thread zugeordnet",
                              "en": "Codex terminal {handle}: no thread found"},
    "log_codex_bild": {"de": "Codex-Stopp: Bildschirm nicht lesbar: {fehler}",
                       "en": "Codex stop: screen not readable: {fehler}"},
    "log_codex_nichts": {"de": "Codex-Stopp {id}: nichts gesendet ({grund}) :: {ausschnitt}",
                         "en": "Codex stop {id}: nothing sent ({grund}) :: {ausschnitt}"},
    "log_tick_laeuft": {"de": "tick: vorheriger Durchlauf läuft noch – übersprungen",
                        "en": "tick: previous run still active – skipped"},
    "log_tickfehler": {"de": "TICK-FEHLER {typ}: {fehler} | {spur}", "en": "TICK ERROR {typ}: {fehler} | {spur}"},
    "log_hook_block": {"de": "HOOK Stop-Block (Sicherungsauftrag) in {sid}",
                       "en": "HOOK stop block (checkpoint request) in {sid}"},
    "log_hook_fehler": {"de": "HOOK-FEHLER {ev}: {typ}: {fehler}", "en": "HOOK ERROR {ev}: {typ}: {fehler}"},
    "log_meldung": {"de": "MELDUNG{modus} p{prio}: {text}", "en": "NOTIFY{modus} p{prio}: {text}"},
    "modus_dry": {"de": " (dry-run)", "en": " (dry-run)"},
    "modus_still": {"de": " (pausiert, still)", "en": " (paused, silent)"},
    "log_kein_topic": {"de": "ntfy: kein Topic im Schlüsselbund – Push übersprungen",
                       "en": "ntfy: no topic in the keychain – push skipped"},
    "log_ntfy_fehler": {"de": "ntfy-Fehler: {typ}", "en": "ntfy error: {typ}"},
    "log_banner_fehler": {"de": "Banner-Fehler", "en": "banner error"},
    "log_konfig_fehler": {"de": "KONFIG-FEHLER in {datei}: {fehler} – nutze Standardwerte",
                          "en": "CONFIG ERROR in {datei}: {fehler} – using defaults"},
    "log_pause": {"de": "Pause {wie}", "en": "Pause {wie}"},
    "log_pause_ende": {"de": "Pause beendet", "en": "Pause ended"},
    "orca_zeit": {"de": "Zeitüberschreitung bei orca {befehl}", "en": "timeout running orca {befehl}"},
    "orca_start": {"de": "orca nicht ausführbar: {fehler}", "en": "cannot run orca: {fehler}"},
    "orca_json": {"de": "keine JSON-Antwort von orca {befehl} (Exit {code})",
                  "en": "no JSON reply from orca {befehl} (exit {code})"},
    "orca_dry_senden": {"de": "DRY-RUN: würde senden an {handle}: {was}", "en": "DRY-RUN: would send to {handle}: {was}"},
    "orca_dry_erstellen": {"de": "DRY-RUN: würde Terminal erstellen in {wo}: {befehl}",
                           "en": "DRY-RUN: would create a terminal in {wo}: {befehl}"},
    "wach_dry": {"de": "würde caffeinate -i -s -t {sek} starten (bis {zeit})",
                 "en": "would start caffeinate -i -s -t {sek} (until {zeit})"},
    "wach_fehler": {"de": "caffeinate fehlgeschlagen: {fehler}", "en": "caffeinate failed: {fehler}"},
    "wach_start": {"de": "caffeinate -i -s bis {zeit} gestartet (pid {pid})",
                   "en": "caffeinate -i -s started until {zeit} (pid {pid})"},

    # ------------------------------------------------------------ Bildschirm-Einordnung (Gründe)
    "bs_leer": {"de": "kein Bildschirminhalt", "en": "empty screen"},
    "bs_menue": {"de": "Menü/Abfrage sichtbar ({m})", "en": "menu/prompt visible ({m})"},
    "bs_eingebaut": {"de": "eingebautes Warten sichtbar ({m})", "en": "built-in wait visible ({m})"},
    "bs_geld": {"de": "Kauf-/Kostenhinweis sichtbar ({m})", "en": "purchase/billing hint visible ({m})"},
    "bs_stale": {"de": "wartet auf Enter nach Schlaf", "en": "waiting for Enter after sleep"},
    "bs_arbeitet": {"de": "Agent arbeitet", "en": "agent is working"},
    "bs_codex_bereit": {"de": "Eingabezeile sichtbar", "en": "input line visible"},
    "bs_bereit": {"de": "leere Eingabezeile", "en": "empty input line"},
    "bs_belegt": {"de": "in der Eingabezeile steht schon Text", "en": "the input line already contains text"},
    "bs_keine": {"de": "keine Eingabezeile erkannt", "en": "no input line found"},

    # ------------------------------------------------------------ Bericht
    "bericht_titel": {"de": "# Limit-Wächter – Bericht {datum}", "en": "# Limit Watchdog – report {datum}"},
    "bericht_zeitraum": {"de": "Zeitraum: {von} bis {bis}", "en": "Period: {von} to {bis}"},
    "bericht_leer": {"de": "Keine Limit-Ereignisse.", "en": "No limit events."},
    "b_gestoppt": {"de": "Geordnet gestoppt", "en": "Stopped in an orderly way"},
    "b_limit": {"de": "Limit erreicht", "en": "Limit reached"},
    "b_fortgesetzt": {"de": "Fortgesetzt", "en": "Continued"},
    "b_blockiert": {"de": "Nicht fortgesetzt (Menü, Kaufhinweis oder unklar)",
                    "en": "Not continued (menu, billing option or unclear screen)"},
    "b_haengt": {"de": "Nach Fortsetzung an einer Abfrage hängen geblieben",
                 "en": "Stuck at a prompt after continuing"},
    "b_freigabe_blockiert": {"de": "Vom Auto-Modus blockiert", "en": "Denied by auto mode"},
    "b_wartet_auf_freigabe": {"de": "Wartete auf eine Freigabe", "en": "Waited for a permission prompt"},
    "b_reserve_gesperrt": {"de": "Eingebaute Fortsetzung wegen Wochenreserve gesperrt",
                           "en": "Built-in continuation blocked by the weekly reserve"},
    "b_ueberziehung": {"de": "Extra-Usage aktiv (prüfen!)", "en": "Extra usage active (check!)"},
    "b_eingebaut": {"de": "Claudes eingebaute Fortsetzung", "en": "Claude's built-in continuation"},
    "b_meldung": {"de": "Gesendete Meldungen", "en": "Notifications sent"},

    # ------------------------------------------------------------ Kommandozeile
    "cli_beschreibung": {"de": "Limit-Wächter für Claude Code und Codex (Orca, Terminal, Desktop)",
                         "en": "Limit Watchdog for Claude Code and Codex (Orca, terminal, desktop)"},
    "h_status": {"de": "Füllstand, Phasen, wartende Sitzungen", "en": "usage, phases, waiting sessions"},
    "h_alle": {"de": "auch aktive Sitzungen zeigen", "en": "also show active sessions"},
    "h_tick": {"de": "ein Durchlauf (macht der LaunchAgent jede Minute)",
               "en": "run once (the LaunchAgent does this every minute)"},
    "h_dry": {"de": "mit Kopie des Zustands, nichts senden", "en": "use a copy of the state, send nothing"},
    "h_simulate": {"de": "Probelauf ohne Verbrauch", "en": "dry run without using any quota"},
    "h_sitzung": {"de": "nur 'stop': scharf, aber nur für diese Claude-Session-ID",
                  "en": "'stop' only: live, but only for this Claude session ID"},
    "h_pause": {"de": "pausieren: pause [30m|2h|1d], beenden: pause aus",
                "en": "pause: pause [30m|2h|1d], end: pause off"},
    "h_weiter": {"de": "Pause beenden", "en": "end the pause"},
    "h_report": {"de": "Bericht der letzten Stunden", "en": "report for the last hours"},
    "h_ntfy_setup": {"de": "zufälliges Topic im Schlüsselbund anlegen", "en": "create a random topic in the keychain"},
    "h_ntfy_abo": {"de": "Topic in die Zwischenablage (zum Abonnieren in der ntfy-App)",
                   "en": "copy the topic to the clipboard (to subscribe in the ntfy app)"},
    "h_test_push": {"de": "Test-Push senden", "en": "send a test notification"},
    "st_kopf": {"de": "Limit-Wächter {version} · {zeit}", "en": "Limit Watchdog {version} · {zeit}"},
    "st_letzter": {"de": "letzter Tick vor {dauer}", "en": "last tick {dauer} ago"},
    "st_kein_tick": {"de": "noch kein Tick", "en": "no tick yet"},
    "st_pausiert_bis": {"de": "PAUSIERT bis {zeit}", "en": "PAUSED until {zeit}"},
    "st_pausiert": {"de": "PAUSIERT (bis pause aus)", "en": "PAUSED (until pause off)"},
    "st_aktiv": {"de": "aktiv", "en": "active"},
    "st_wachter": {"de": "Wächter: {pause} · {lauf} · LaunchAgent {agent}",
                   "en": "Watchdog: {pause} · {lauf} · LaunchAgent {agent}"},
    "st_geladen": {"de": "geladen", "en": "loaded"},
    "st_nicht_geladen": {"de": "NICHT geladen", "en": "NOT loaded"},
    "st_orca_weg": {"de": "Orca: NICHT erreichbar ({fehler})", "en": "Orca: NOT reachable ({fehler})"},
    "st_daten": {"de": "Daten vor {dauer} ({quelle})", "en": "data {dauer} old ({quelle})"},
    "st_keine_daten": {"de": "keine Daten", "en": "no data"},
    "st_reserve": {"de": " · Reserve erreicht", "en": " · reserve reached"},
    "st_zeile": {"de": "{name:7} 5h {f5:22} Woche {fw:22} Phase {phase:8} {alter}",
                 "en": "{name:7} 5h {f5:22} week {fw:22} phase {phase:8} {alter}"},
    "st_fenster": {"de": "{pct} (Reset {reset})", "en": "{pct} (resets {reset})"},
    "st_schwellen": {
        "de": "Schwellen: Warnung {w} %, Stopp {s} % (5h) · Woche {ww}/{ws} % · Reserve {r} % "
              "(ab {ab} % Woche keine Auto-Fortsetzung)",
        "en": "Thresholds: warn {w}%, stop {s}% (5h) · week {ww}/{ws}% · reserve {r}% "
              "(no auto-continue above {ab}% weekly use)",
    },
    "st_sitzungen": {"de": "Sitzungen (letzte 2 Tage): {c} Claude, {x} Codex",
                     "en": "Sessions (last 2 days): {c} Claude, {x} Codex"},
    "st_ab": {"de": " · Fortsetzung ab {zeit}", "en": " · continues from {zeit}"},
    "st_keine_wartet": {"de": "  (keine Sitzung wartet oder ist blockiert; alle anzeigen: status --alle)",
                        "en": "  (no session is waiting or blocked; show all: status --all)"},
    "ja": {"de": "ja", "en": "yes"},
    "nein": {"de": "nein", "en": "no"},
    "NEIN": {"de": "NEIN", "en": "NO"},
    "st_mac": {"de": "Mac: Netzteil {ac} · Schlaf aus: {schlaf} · zugeklappt wach: {deckel} · Amphetamine: {amph}",
               "en": "Mac: on power {ac} · sleep disabled: {schlaf} · awake with lid closed: {deckel} · "
                     "Amphetamine: {amph}"},
    "st_ntfy": {"de": "ntfy: Topic im Schlüsselbund {topic} · Wachhalten: {wach}",
                "en": "ntfy: topic in keychain {topic} · keep-awake: {wach}"},
    "st_topic_fehlt": {"de": "FEHLT (waechter.py ntfy-einrichten)", "en": "MISSING (waechter.py ntfy-setup)"},
    "st_caffeinate": {"de": "caffeinate bis {zeit}", "en": "caffeinate until {zeit}"},
    "st_aus": {"de": "aus", "en": "off"},
    "st_log": {"de": "Log: {pfad}", "en": "Log: {pfad}"},
    "phase_ok": {"de": "OK", "en": "OK"},
    "phase_warnung": {"de": "WARNUNG", "en": "WARNING"},
    "phase_stopp": {"de": "STOPP", "en": "STOP"},
    "phase_limit": {"de": "LIMIT", "en": "LIMIT"},
    "tick_dry": {"de": "Tick im Dry-Run (Kopie des Zustands, nichts gesendet)",
                 "en": "Tick in dry-run (copy of the state, nothing sent)"},
    "zyklus_fertig": {"de": "Zyklus fertig: alles mit Probedaten und Orca-Attrappe, nichts gesendet.",
                      "en": "Cycle finished: all with sample data and a fake Orca, nothing sent."},
    "nur_stop": {"de": "--sitzung gibt es nur für 'simulate stop'.", "en": "--session only works with 'simulate stop'."},
    "pause_ende": {"de": "Wächter wieder aktiv.", "en": "Watchdog active again."},
    "pause_dauer": {"de": "Dauer wie 30m, 2h oder 1d angeben (oder 'aus').",
                    "en": "Give a duration like 30m, 2h or 1d (or 'off')."},
    "pause_bis": {"de": "bis {zeit}", "en": "until {zeit}"},
    "pause_ohne_ende": {"de": "ohne Ende", "en": "without end"},
    "pause_bis_aus": {"de": "bis: waechter.py pause aus", "en": "until: waechter.py pause off"},
    "pause_ok": {"de": "Wächter pausiert {wie}. Keine Stopps, keine Fortsetzungen, keine Pushes; Claudes "
                       "eingebaute Fortsetzung läuft normal.",
                 "en": "Watchdog paused {wie}. No stops, no continuations, no notifications; Claude's built-in "
                       "auto-continue works as usual."},
    "ntfy_schon": {"de": "Topic ist schon im Schlüsselbund (Dienst {dienst}).",
                   "en": "The topic is already in the keychain (service {dienst})."},
    "ntfy_fehler": {"de": "Konnte das Topic nicht im Schlüsselbund speichern.",
                    "en": "Could not store the topic in the keychain."},
    "ntfy_neu": {"de": "Zufälliges ntfy-Topic erzeugt und im Schlüsselbund gespeichert (Dienst {dienst}).",
                 "en": "Created a random ntfy topic and stored it in the keychain (service {dienst})."},
    "ntfy_label": {"de": "Limit-Wächter ntfy-Topic", "en": "Limit Watchdog ntfy topic"},
    "ntfy_keins": {"de": "Kein Topic im Schlüsselbund. Erst: waechter.py ntfy-einrichten",
                   "en": "No topic in the keychain. First run: waechter.py ntfy-setup"},
    "ntfy_abo_1": {"de": "Das Topic liegt jetzt in der Zwischenablage (auch auf dem iPhone per Universal Clipboard).",
                   "en": "The topic is now on the clipboard (also on your iPhone via Universal Clipboard)."},
    "ntfy_abo_2": {"de": "ntfy-App → + → Topic einfügen → Server ntfy.sh lassen → Abonnieren. Danach: waechter.py test-push",
                   "en": "ntfy app → + → paste topic → keep server ntfy.sh → Subscribe. Then: waechter.py test-push"},
    "test_ok": {"de": "Test-Push gesendet (und macOS-Banner).", "en": "Test notification sent (and a macOS banner)."},

    # ------------------------------------------------------------ Sitzungszustände (Anzeige)
    "z_aktiv": {"de": "aktiv", "en": "active"},
    "z_sicherung": {"de": "sichert gerade", "en": "checkpointing"},
    "z_gestoppt": {"de": "gestoppt", "en": "stopped"},
    "z_limit": {"de": "am Limit", "en": "at limit"},
    "z_eingebaut_wartet": {"de": "Claude wartet selbst", "en": "Claude waiting (built-in)"},
    "z_eingebaut_fortgesetzt": {"de": "von Claude fortgesetzt", "en": "continued by Claude"},
    "z_stale": {"de": "wartet auf Enter", "en": "waiting for Enter"},
    "z_disabled": {"de": "Claude-Warten beendet", "en": "built-in wait ended"},
    "z_fortgesetzt": {"de": "fortgesetzt", "en": "continued"},
    "z_blockiert": {"de": "blockiert – bitte ansehen", "en": "blocked – please check"},
    "z_reserve": {"de": "Wochenreserve", "en": "weekly reserve"},
    "z_aufgegeben": {"de": "aufgegeben", "en": "gave up"},
    "z_beendet": {"de": "beendet", "en": "ended"},

    # ------------------------------------------------------------ Installer
    "inst_abbruch": {"de": "ABBRUCH: fremde Einträge hätten sich geändert – nichts geschrieben.",
                     "en": "ABORTED: entries of other tools would have changed – nothing written."},
    "inst_ok_eintragen": {"de": "eingetragen: {anzahl} Hookgruppen in {datei}",
                          "en": "installed: {anzahl} hook groups in {datei}"},
    "inst_ok_austragen": {"de": "ausgetragen: {anzahl} Hookgruppen verbleiben in {datei}",
                          "en": "removed: {anzahl} hook groups remain in {datei}"},

    # ------------------------------------------------------------ Simulation
    "sim_jetzt": {"de": "Simulation {fall} {anbieter} (echte Terminals nur gelesen, nichts gesendet)",
                  "en": "Simulation {fall} {anbieter} (real terminals only read, nothing sent)"},
    "sim_hooks": {"de": "  Claude-Hooks in dieser Phase: neue Agent/Workflow-Aufrufe -> deny; "
                        "Turn-Ende -> einmal Sicherungsauftrag (decision=block).",
                  "en": "  Claude hooks in this phase: new Agent/Workflow calls -> deny; "
                        "end of turn -> one checkpoint request (decision=block)."},
    "sim_gestoppt": {"de": "  (Sandbox: {anzahl} registrierte {anbieter}-Sitzung(en) als 'gestoppt' markiert)",
                     "en": "  (sandbox: marked {anzahl} registered {anbieter} session(s) as 'stopped')"},
    "sim_zeile": {"de": "  {a:6} Phase {phase:8} 5h {p5:5.1f} %  Woche {pw:5.1f} %",
                  "en": "  {a:6} phase {phase:8} 5h {p5:5.1f}%  week {pw:5.1f}%"},
    "sim_push": {"de": "  PUSH p{prio}: {text}", "en": "  PUSH p{prio}: {text}"},
    "sim_aktion": {"de": "  AKTION: {text}", "en": "  ACTION: {text}"},
    "sim_nichts": {"de": "  (keine Meldung, keine Aktion)", "en": "  (no notification, no action)"},
    "sim_s1": {"de": "1 Normalbetrieb", "en": "1 normal operation"},
    "sim_s2": {"de": "2 Warnschwelle", "en": "2 warning threshold"},
    "sim_s3": {"de": "3 Stopp-Schwelle", "en": "3 stop threshold"},
    "sim_s4": {"de": "4 Limit erreicht", "en": "4 limit reached"},
    "sim_s5": {"de": "5 Reset + 3 min", "en": "5 reset + 3 min"},
    "sim_s6": {"de": "6 Reset + 6 min", "en": "6 reset + 6 min"},
    "sim_s7": {"de": "7 Morgenbericht", "en": "7 morning report"},
    "sim_hook_deny": {"de": "  HOOK PreToolUse(Agent): {wert}", "en": "  HOOK PreToolUse(Agent): {wert}"},
    "sim_hook_post": {"de": "  HOOK PostToolUse: {wert}", "en": "  HOOK PostToolUse: {wert}"},
    "sim_hook_stop": {"de": "  HOOK Stop #1: {eins} | Stop #2 (stop_hook_active): {zwei}",
                      "en": "  HOOK Stop #1: {eins} | Stop #2 (stop_hook_active): {zwei}"},
    "sim_frei": {"de": "frei", "en": "allowed"},
    "sim_ende": {"de": "\n== Endzustand ==", "en": "\n== Final state =="},
    "sim_gesendet": {"de": "  An die Attrappe gesendet:", "en": "  Sent to the fake Orca:"},
    "sim_scharf": {"de": "Simulierte Stopp-Phase für Sitzung {sid} ist {minuten} min aktiv (nur diese Sitzung).",
                   "en": "Simulated stop phase for session {sid} is active for {minuten} min (this session only)."},
    "sim_scharf_ende": {"de": "Beenden: waechter.py simulate aus", "en": "End it with: waechter.py simulate off"},
    "sim_aus": {"de": "Simulation beendet.", "en": "Simulation ended."},

    # ------------------------------------------------------------ v1.1 Nachtmodus: Tick, CLI, Bericht, Simulation (Umsetzer A)
    "z_wartet_auf_weiter": {"de": "wartet auf „weiter“", "en": "waiting for \"continue\""},
    "push_wartet_auf_weiter": {"de": "{n}: Limit zurückgesetzt – {anzahl} Sitzung(en) warten auf „weiter“.",
                               "en": "{n}: limit has reset – {anzahl} session(s) waiting for you to type \"continue\"."},
    "b_wartet_auf_weiter": {"de": "Ohne Nachtmodus nicht fortgesetzt (wartet auf „weiter“)",
                            "en": "Not continued without night mode (waiting for \"continue\")"},
    "b_eingebaut_gesperrt": {"de": "Eingebaute Fortsetzung gesperrt (kein Nachtmodus)",
                             "en": "Built-in continuation blocked (no night mode)"},
    "b_nachtmodus": {"de": "Nachtmodus geschaltet", "en": "Night mode switched"},
    "h_nacht": {"de": "Nachtmodus: status | an [sitzung|alle] | aus [sitzung|alle]",
                "en": "Night mode: status | on [session|all] | off [session|all]"},
    "n_an_alle": {"de": "Nachtmodus an für alle Sitzungen bis {zeit}.", "en": "Night mode on for all sessions until {zeit}."},
    "n_an": {"de": "Nachtmodus an für {sitzung} bis {zeit}.", "en": "Night mode on for {sitzung} until {zeit}."},
    "n_aus_alle": {"de": "Nachtmodus aus (global und für alle Sitzungen).",
                   "en": "Night mode off (global and for all sessions)."},
    "n_aus": {"de": "Nachtmodus aus für {sitzung}.", "en": "Night mode off for {sitzung}."},
    "n_global_noch": {"de": "Hinweis: Nachtmodus für alle Sitzungen ist noch an bis {zeit} (aus: nacht aus alle).",
                      "en": "Note: night mode for all sessions is still on until {zeit} (off: night off all)."},
    "n_keine": {"de": "Keine Sitzung passt zu „{ziel}“. Bekannte Sitzungen:",
                "en": "No session matches \"{ziel}\". Known sessions:"},
    "n_mehrdeutig": {"de": "„{ziel}“ ist mehrdeutig – bitte genauer (ID-Anfang):",
                     "en": "\"{ziel}\" is ambiguous – please be more specific (ID prefix):"},
    "n_keine_liste": {"de": "  (keine)", "en": "  (none)"},
    "n_aktion": {"de": "Unbekannte Aktion „{aktion}“ – erlaubt: status, an, aus.",
                 "en": "Unknown action \"{aktion}\" – allowed: status, on, off."},
    "n_global_an": {"de": "Nachtmodus: an für alle Sitzungen bis {zeit}", "en": "Night mode: on for all sessions until {zeit}"},
    "n_global_aus": {"de": "Nachtmodus für alle: aus", "en": "Night mode for all sessions: off"},
    "n_schon_wartend": {"de": "{anzahl} Sitzung(en) warten schon auf „weiter“ – der Wächter setzt sie in der "
                              "nächsten Minute fort (mit Bildschirmprüfung):",
                        "en": "{anzahl} session(s) already wait for \"continue\" – the watchdog continues them "
                              "within the next minute (after checking the screen):"},
    "n_meta_aktion": {"de": "aktion", "en": "action"},
    "n_hilfe_aktion": {"de": "status | an | aus", "en": "status | on | off"},
    "n_meta_ziel": {"de": "ziel", "en": "target"},
    "n_hilfe_ziel": {"de": "alle | ID-Anfang | Projektordner", "en": "all | ID prefix | project folder"},
    "n_sitzungen": {"de": "Sitzungen im Nachtmodus:", "en": "Sessions in night mode:"},
    "n_nur_nacht_aus": {"de": "Hinweis: nur_mit_nachtmodus = false – alle Sitzungen werden fortgesetzt.",
                        "en": "Note: nur_mit_nachtmodus = false – all sessions are continued."},
    "st_nacht": {"de": " · Nacht bis {zeit}", "en": " · night until {zeit}"},
    "st_weiter_noetig": {"de": " · nach Reset {zeit} „weiter“ nötig", "en": " · after reset {zeit} type \"continue\""},
    "sim_hook_nacht": {"de": "  Hook #nacht in A: {wert}", "en": "  Hook #night in A: {wert}"},

    # ------------------------------------------------------------ v1.1 Nachtmodus: Hook und Agententexte (Umsetzer B)
    "nach_reset_weiter": {"de": " Nach dem Reset setzt {wer} mit „weiter“ fort.",
                          "en": " After the reset, {wer} will continue by typing \"continue\"."},
    "nacht_an_hook": {
        "de": "{app}: Nachtmodus an bis {zeit} – nach einem Limit-Reset setze ich diese Sitzung automatisch fort. "
              "Aus: #nacht aus",
        "en": "{app}: Night mode on until {zeit} – after a limit reset I will continue this session automatically. "
              "Off: #night off",
    },
    "nacht_alle_hook": {
        "de": "{app}: Nachtmodus an für alle Sitzungen bis {zeit} – nach einem Limit-Reset setze ich sie "
              "automatisch fort. Aus: #nacht aus",
        "en": "{app}: Night mode on for all sessions until {zeit} – after a limit reset I will continue them "
              "automatically. Off: #night off",
    },
    "nacht_aus_hook": {
        "de": "{app}: Nachtmodus aus – nach einem Reset wartet diese Sitzung auf „weiter“.",
        "en": "{app}: Night mode off – after a reset this session waits for you to type \"continue\".",
    },
    "nacht_aus_global_hook": {
        "de": "{app}: Nachtmodus für diese Sitzung aus – für alle Sitzungen ist er aber noch an bis {zeit} "
              "(aus: waechter.py nacht aus alle).",
        "en": "{app}: Night mode off for this session – but it is still on for all sessions until {zeit} "
              "(off: waechter.py night off all).",
    },

    # ------------------------------------------------------------ v1.2 Schwellen-Befehl
    "h_schwellen": {"de": "Schwellen anzeigen oder setzen (schwellen setzen warnung=80 …)",
                    "en": "show or set thresholds (thresholds set warn=80 …)"},
    "sw_zeile": {"de": "{name:16} {wert}", "en": "{name:16} {wert}"},
    "sw_gespeichert": {"de": "Schwellen gespeichert in {datei}.", "en": "Thresholds saved to {datei}."},
    "sw_aktion": {"de": "Unbekannte Aktion „{aktion}“ – erlaubt: setzen.", "en": "Unknown action \"{aktion}\" – allowed: set."},
    "sw_leer": {"de": "Keine Werte angegeben (z. B. warnung=80).", "en": "No values given (e.g. warn=80)."},
    "sw_format": {"de": "„{teil}“: erwartet schluessel=wert", "en": "\"{teil}\": expected key=value"},
    "sw_schluessel": {"de": "Unbekannter Schlüssel „{name}“", "en": "Unknown key \"{name}\""},
    "sw_zahl": {"de": "{name}: ganze Zahl von {min} bis {max} erwartet", "en": "{name}: whole number from {min} to {max} expected"},
    "sw_fehler": {"de": "Nicht gespeichert: {fehler}", "en": "Not saved: {fehler}"},

    # ------------------------------------------------------------ v1.2 Menüleisten-App
    "app_titel": {"de": "Limit-Wächter", "en": "Limit Watchdog"},
    "app_version": {"de": "Version {version}", "en": "Version {version}"},
    "app_aktiv": {"de": "Wächter aktiv", "en": "Watchdog active"},
    "app_waechter_aus": {"de": "Wächter läuft nicht – LaunchAgent nicht geladen",
                         "en": "Watchdog not running – LaunchAgent not loaded"},
    "app_kein_tick": {"de": "Noch kein Lauf", "en": "No run yet"},
    "app_letzter_tick": {"de": "Letzter Lauf vor {dauer}", "en": "Last run {dauer} ago"},
    "app_orca_fehlt": {"de": "Orca nicht erreichbar", "en": "Orca not reachable"},
    "app_fuenf": {"de": "5 h", "en": "5 h"},
    "app_woche": {"de": "Woche", "en": "Week"},
    "app_reset": {"de": "Reset {zeit}", "en": "Resets {zeit}"},
    "app_keine_daten": {"de": "Keine Daten", "en": "No data"},
    "app_veraltet": {"de": "Daten veraltet ({dauer})", "en": "Data stale ({dauer})"},
    "app_reserve_erreicht": {"de": "Wochenreserve erreicht", "en": "Weekly reserve reached"},
    "app_pause": {"de": "Pause", "en": "Pause"},
    "app_pausiert": {"de": "Pausiert", "en": "Paused"},
    "app_pausiert_bis": {"de": "Pausiert bis {zeit}", "en": "Paused until {zeit}"},
    "app_pause_30m": {"de": "30 min", "en": "30 min"},
    "app_pause_2h": {"de": "2 h", "en": "2 h"},
    "app_pause_offen": {"de": "Unbegrenzt", "en": "Until resumed"},
    "app_morgen": {"de": "morgen {zeit}", "en": "tomorrow {zeit}"},
    "app_pause_ende": {"de": "Pause beenden", "en": "End pause"},
    "app_nacht": {"de": "Nachtmodus", "en": "Night mode"},
    "app_nacht_alle": {"de": "Alle Sitzungen bis {zeit}", "en": "All sessions until {zeit}"},
    "app_nacht_aus": {"de": "Nachtmodus aus", "en": "Night mode off"},
    "app_nacht_sitzung": {"de": "Nacht bis {zeit}", "en": "Night until {zeit}"},
    "app_nacht_geerbt": {"de": "Über Nacht (alle) bis {zeit} – für alle ausschalten über die Kachel „Nacht“",
                         "en": "Overnight (all) until {zeit} – turn it off for all with the “Night” tile"},
    "app_nacht_hinweis": {"de": "Claude setzt nach dem Reset selbst fort. Im Nachtmodus springt der Wächter ein, "
                                "wenn das nicht greift, setzt Codex fort und hält den Mac wach.",
                          "en": "Claude continues by itself after the reset. In night mode the watchdog steps in when "
                                "that fails, continues Codex and keeps the Mac awake."},
    "app_sitzungen": {"de": "Sitzungen", "en": "Sessions"},
    "app_keine_sitzungen": {"de": "Keine Sitzungen", "en": "No sessions"},
    "app_fortsetzung_ab": {"de": "Fortsetzung ab {zeit}", "en": "Continues at {zeit}"},
    "app_weiter_noetig": {"de": "„weiter“ nötig", "en": "type \"continue\""},
    "app_schwellen": {"de": "Schwellen", "en": "Thresholds"},
    "app_warnung": {"de": "Warnung (5 h)", "en": "Warning (5 h)"},
    "app_stopp": {"de": "Stopp (5 h)", "en": "Stop (5 h)"},
    "app_woche_warnung": {"de": "Warnung (Woche)", "en": "Warning (week)"},
    "app_woche_stopp": {"de": "Stopp (Woche)", "en": "Stop (week)"},
    "app_reserve": {"de": "Wochenreserve", "en": "Weekly reserve"},
    "app_speichern": {"de": "Speichern", "en": "Save"},
    "app_gespeichert": {"de": "Gespeichert", "en": "Saved"},
    "app_fehler": {"de": "Fehler: {fehler}", "en": "Error: {fehler}"},
    "app_bericht": {"de": "Bericht (24 h)", "en": "Report (24 h)"},
    "app_bericht_leer": {"de": "Kein Bericht", "en": "No report"},
    "app_log_oeffnen": {"de": "Log öffnen", "en": "Open log"},
    "app_aktualisieren": {"de": "Aktualisieren", "en": "Refresh"},
    "app_beenden": {"de": "App beenden", "en": "Quit app"},
    "app_schliessen": {"de": "Schließen", "en": "Close"},
    "kf_bereich": {"de": "{name} muss zwischen 0 und 100 liegen", "en": "{name} must be between 0 and 100"},
    "kf_warnung_stopp": {"de": "schwellen.warnung muss kleiner als schwellen.stopp sein",
                         "en": "schwellen.warnung (warn) must be lower than schwellen.stopp (stop)"},
    "kf_woche": {"de": "schwellen.woche_warnung darf nicht größer als woche_stopp sein",
                 "en": "schwellen.woche_warnung (weekly warn) must not exceed woche_stopp (weekly stop)"},
    "app_python_fehlt": {"de": "Python oder waechter.py nicht gefunden: {pfad}",
                         "en": "Python or waechter.py not found: {pfad}"},
    "app_min": {"de": "{n} min", "en": "{n} min"},
    "app_std": {"de": "{h} h {m} min", "en": "{h} h {m} min"},

    # ------------------------------------------------------------ v1.3: Orte und Fähigkeiten (Vertrag, Integrator)
    "ort_orca": {"de": "Orca", "en": "Orca"},
    "ort_terminal": {"de": "Terminal", "en": "Terminal"},
    "ort_desktop": {"de": "Desktop", "en": "Desktop"},
    "f_warnt": {"de": "warnt", "en": "warns"},
    "f_stoppt": {"de": "stoppt", "en": "stops"},
    "f_stoppt_nicht": {"de": "stoppt nicht", "en": "no stop"},
    "f_setzt_fort": {"de": "setzt fort", "en": "continues"},
    "f_nur_push": {"de": "nur Push", "en": "push only"},
    "f_kein_fortsetzen": {"de": "kein Fortsetzen", "en": "no auto-continue"},
    "f_trenner": {"de": " · ", "en": " · "},
    "st_orca_fehlt": {"de": "Orca: nicht installiert – normale Terminals werden trotzdem überwacht",
                      "en": "Orca: not installed – normal terminals are still watched"},
    "st_sl_aktiv": {"de": "Claude-Füllstand: Statusline-Kette aktiv (zuletzt vor {dauer})",
                    "en": "Claude usage: status line chain active (last update {dauer} ago)"},
    "st_sl_aktiv_leer": {"de": "Claude-Füllstand: Statusline-Kette aktiv (noch keine Daten)",
                         "en": "Claude usage: status line chain active (no data yet)"},
    "st_sl_zurueck": {"de": "Statusline-Kette fehlt – die Statusline wurde ersetzt (z. B. von Orca). Füllstand kommt jetzt nur noch von "
                            "Orca (falls installiert). Neu einrichten: ./install.sh",
                      "en": "Status line chain missing – the status line was replaced (e.g. by Orca). Usage now comes from Orca "
                            "only (if installed). Set up again: ./install.sh"},
    "st_sl_aus": {"de": "Statusline-Kette nicht eingerichtet (./install.sh)",
                  "en": "Status line chain not set up (./install.sh)"},
    "sl_anzeige": {"de": "5h {p5} · Woche {pw}", "en": "5h {p5} · week {pw}"},
    "push_weiter_befehl": {"de": "{n} außerhalb von Orca: weiter mit „weiter“ in der Sitzung oder {befehl}",
                           "en": "{n} outside Orca: type \"continue\" in the session or run {befehl}"},
    "app_statusline_fehlt": {"de": "Statusline-Kette fehlt – ./install.sh erneut ausführen",
                             "en": "Status line chain missing – run ./install.sh again"},

    # ---- v1.3 U1 (Statusline-Kette im Installer)
    "inst_sl_ein": {"de": "Statusline-Kette eingetragen in {datei} (bisherige Statusline läuft weiter)",
                    "en": "status line chain added to {datei} (the previous status line keeps running)"},
    "inst_sl_gesichert": {"de": "   bisherige Statusline gesichert: {datei}", "en": "   previous status line saved: {datei}"},
    "inst_sl_aus": {"de": "Statusline wiederhergestellt in {datei}", "en": "status line restored in {datei}"},
    "inst_sl_fremd": {"de": "Statusline ist nicht (mehr) die des Wächters – nicht angefasst.",
                      "en": "The status line is not (or no longer) the watchdog's – left untouched."},
    "inst_sl_ohne_original": {"de": "Keine gesicherte Statusline gefunden – Eintrag des Wächters wird entfernt.",
                              "en": "No saved status line found – removing the watchdog's entry."},
    # ---- v1.3 U2 (Codex und Fortsetzen ohne Orca)
    "log_codex_queue_dry": {"de": "DRY-RUN: würde per codex queue an {id} senden: {text}",
                            "en": "DRY-RUN: would send via codex queue to {id}: {text}"},
    "log_codex_queue_fehler": {"de": "codex queue an {id} fehlgeschlagen: {fehler}",
                               "en": "codex queue to {id} failed: {fehler}"},
    # ---- v1.4: Füllstand (offizielle Nutzungsanzeige) ----
    "nz_log_fehler": {"de": "Offizielle Nutzungsanzeige {n} nicht verfügbar ({fehler}) – Rückfall auf Orca/Statusline",
                      "en": "Official usage for {n} not available ({fehler}) - falling back to Orca/status line"},
    "nz_log_ok": {"de": "Offizielle Nutzungsanzeige {n} wieder verfügbar",
                  "en": "Official usage for {n} available again"},
    "nz_log_frueh": {"de": "{n}: {art}-Fenster vorzeitig zurückgesetzt – wartende Sitzungen sind sofort fällig",
                     "en": "{n}: {art} window reset early - waiting sessions are due now"},
    "nz_log_vorgezogen": {"de": "{n}: Reset des {art}-Fensters vorgezogen auf {zeit} – wartende Sitzungen folgen dann",
                          "en": "{n}: {art} window reset moved forward to {zeit} - waiting sessions follow then"},
    "nz_push_frueh": {"de": "{n}: Limit ({art}) wurde vorzeitig zurückgesetzt. Wartende Sitzungen werden jetzt fortgesetzt.",
                      "en": "{n}: the {art} limit was reset early. Waiting sessions continue now."},
    "nz_push_abgelaufen": {"de": "{n}: offizielle Werte nicht verfügbar, Anmeldung abgelaufen – Orca-Werte können hinterherhängen. Einmal {n} öffnen, dann stimmen sie wieder.",
                           "en": "{n}: official usage unavailable, login expired - Orca values may lag behind. Open {n} once to fix it."},
    "nz_q_offiziell": {"de": "offiziell", "en": "official"},
    "nz_q_orca": {"de": "Orca", "en": "Orca"},
    "nz_q_statusline": {"de": "Statusline", "en": "status line"},
    "nz_q_rollout": {"de": "Codex-Protokoll", "en": "Codex log"},
    "nz_q_keine": {"de": "keine Daten", "en": "no data"},
    "nz_f_auth": {"de": "Anmeldung abgelehnt", "en": "login rejected"},
    "nz_f_rate": {"de": "zu viele Abrufe, später erneut", "en": "too many requests, retrying later"},
    "nz_f_netz": {"de": "Netzwerkfehler", "en": "network error"},
    "nz_f_format": {"de": "Antwort unlesbar", "en": "unreadable response"},
    "nz_f_kein_token": {"de": "nicht angemeldet", "en": "not logged in"},
    "nz_f_abgelaufen": {"de": "Anmeldung abgelaufen – einmal Claude Code öffnen; bis dahin können die Werte hinterherhängen",
                        "en": "login expired - open Claude Code once; until then values may lag behind"},
    "nz_f_url": {"de": "Adresse nicht erlaubt (nur https zum offiziellen Host)",
                 "en": "address not allowed (https to the official host only)"},
    "nz_f_noch_nicht": {"de": "noch kein Abruf", "en": "not fetched yet"},
    "nz_st_ok": {"de": "{n}-Quelle: {quelle} (vor {dauer})", "en": "{n} source: {quelle} ({dauer} ago)"},
    "nz_st_keine": {"de": "{n}-Quelle: keine Daten", "en": "{n} source: no data"},
    "nz_st_fehler": {"de": "   offizielle Anzeige {n}: {grund}", "en": "   official usage {n}: {grund}"},
    "nz_st_aus": {"de": "Offizielle Nutzungsanzeige: aus ([daten] offiziell = false)",
                  "en": "Official usage: off ([daten] offiziell = false)"},
    "nz_g_ok": {"de": "Alles gut", "en": "All good"},
    "nz_g_warnung": {"de": "{n}: Warnung – {pct} (Reset {zeit})", "en": "{n}: warning - {pct} (resets {zeit})"},
    "nz_g_stopp": {"de": "Stopp – Reset {zeit}", "en": "Stop - resets {zeit}"},
    "nz_g_limit": {"de": "Limit – Reset {zeit}", "en": "Limit - resets {zeit}"},
    "nz_g_wartet": {"de": "{anzahl} Sitzung(en) warten", "en": "{anzahl} session(s) waiting"},
    "nz_g_pause": {"de": "Pausiert", "en": "Paused"},
    "nz_g_pause_bis": {"de": "Pausiert bis {zeit}", "en": "Paused until {zeit}"},
    "nz_g_stoerung": {"de": "Wächter läuft nicht", "en": "Watchdog is not running"},
    "nz_g_d_auto": {"de": "{n}: {anzahl} Sitzung(en) werden automatisch fortgesetzt",
                    "en": "{n}: {anzahl} session(s) will continue automatically"},
    "nz_g_d_hand": {"de": "{n}: {anzahl} Sitzung(en) brauchen danach „weiter“",
                    "en": "{n}: {anzahl} session(s) need \"continue\" afterwards"},
    "nz_g_d_anbieter": {"de": "{n}, {art}-Fenster", "en": "{n}, {art} window"},
    "nz_g_d_naechste": {"de": "nächste Fortsetzung {zeit}", "en": "next continuation {zeit}"},
    "nz_g_d_agent": {"de": "LaunchAgent nicht geladen – ./install.sh", "en": "LaunchAgent not loaded - ./install.sh"},
    "nz_g_d_tick": {"de": "letzter Lauf vor {dauer}", "en": "last run {dauer} ago"},
    "nz_g_d_kein_tick": {"de": "noch kein Lauf", "en": "no run yet"},
    "nz_kf_url": {"de": "daten.{name} muss eine https-Adresse auf {host} sein",
                  "en": "daten.{name} must be an https address on {host}"},
    "nz_kf_ganzzahl": {"de": "daten.{name} muss eine ganze Zahl ab 1 sein",
                       "en": "daten.{name} must be a whole number of at least 1"},
    "nz_kf_eng": {"de": "daten.offiziell_intervall_eng_minuten darf nicht größer als offiziell_intervall_minuten sein",
                  "en": "daten.offiziell_intervall_eng_minuten must not be larger than offiziell_intervall_minuten"},
    "nz_kf_alter": {"de": "daten.offiziell_max_alter_minuten muss mindestens offiziell_intervall_minuten sein",
                    "en": "daten.offiziell_max_alter_minuten must be at least offiziell_intervall_minuten"},
    "nz_kf_abfall": {"de": "daten.frueh_reset_abfall muss zwischen 5 und 100 liegen",
                     "en": "daten.frueh_reset_abfall must be between 5 and 100"},

    # ---- v1.4: Fortsetzen mit Belegen ----
    "fs_aktion_nachpruefen": {"de": "LÄUFT OFFENBAR {s} ({grund}) – wird nachgeprüft",
                              "en": "APPARENTLY RUNNING {s} ({grund}) – will be re-checked"},
    "fs_aktion_zurueck": {"de": "NACHPRÜFUNG {s}: keine Aktivität seit dem Reset – zurück ins Warten, neuer Versuch",
                          "en": "RE-CHECK {s}: no activity since the reset – back to waiting, trying again"},
    "fs_log_orca_widerspruch": {"de": "{s}: Orca meldet „working“, Bildschirm und Protokoll sagen {urteil} – Orca ignoriert",
                                "en": "{s}: Orca reports \"working\", screen and log say {urteil} – ignoring Orca"},
    "fs_log_nachpruefung": {"de": "{s}: {anzahl} Nachprüfungen ohne Aktivität – blockiert",
                            "en": "{s}: {anzahl} re-checks without activity – blocked"},
    "fs_grund_unklar": {"de": "läuft laut Orca, aber seit dem Reset keine Aktivität",
                        "en": "running according to Orca, but no activity since the reset"},
    "fs_kf_bereich": {"de": "{name} muss eine ganze Zahl von {min} bis {max} sein",
                      "en": "{name} must be a whole number from {min} to {max}"},
    "fs_kf_bool": {"de": "{name} muss true oder false sein", "en": "{name} must be true or false"},
    "fs_lage_arbeitet": {"de": "arbeitet", "en": "working"},
    "fs_lage_ruht": {"de": "ruht", "en": "idle"},
    "fs_lage_sichert": {"de": "sichert", "en": "checkpointing"},
    "fs_lage_wartet": {"de": "wartet", "en": "waiting"},
    "fs_lage_wartet_bis": {"de": "wartet bis {zeit}", "en": "waiting until {zeit}"},
    "fs_lage_wartet_bis_weiter": {"de": "wartet bis {zeit} – dann „weiter“", "en": "waiting until {zeit} – then \"continue\""},
    "fs_lage_pruefung": {"de": "wird geprüft", "en": "being checked"},
    "fs_lage_weiter_noetig": {"de": "„weiter“ nötig", "en": "\"continue\" needed"},
    "fs_lage_blockiert": {"de": "blockiert", "en": "blocked"},
    "fs_lage_beendet": {"de": "beendet", "en": "ended"},

    # ---- v1.4: Wach-Modus ----
    "wm_dialog_text": {"de": "Mac-Passwort, um die Bildschirmsperre umzuschalten (Wach-Modus):",
                       "en": "Mac password to switch the screen lock (awake mode):"},
    "wm_abbrechen": {"de": "Abbrechen", "en": "Cancel"},
    "wm_ok": {"de": "OK", "en": "OK"},
    "wm_abgebrochen": {"de": "Abgebrochen – nichts geändert.", "en": "Cancelled – nothing changed."},
    "wm_passwort": {"de": "Bildschirmsperre konnte nicht umgeschaltet werden (Passwort falsch?).",
                    "en": "Could not switch the screen lock (wrong password?)."},
    "wm_an": {"de": "Wach-Modus AN: Mac bleibt wach (auch zugeklappt), keine Bildschirmsperre. Netzteil anlassen.",
              "en": "Awake mode ON: the Mac stays awake (also with the lid closed), no screen lock. Keep it on power."},
    "wm_an_amph_fehler": {"de": "Wach-Modus AN: Bildschirmsperre aus. Hinweis: Amphetamine-Sitzung konnte nicht "
                                "gestartet werden – zugeklappt schläft der Mac.",
                          "en": "Awake mode ON: screen lock off. Note: the Amphetamine session could not be started – "
                                "with the lid closed the Mac sleeps."},
    "wm_an_ohne_amph": {"de": "Wach-Modus AN: Bildschirmsperre aus. Amphetamine ist nicht installiert – zugeklappt "
                              "schläft der Mac; am Netzteil hält caffeinate ihn wach, solange eine Fortsetzung "
                              "ansteht oder der Nachtmodus läuft.",
                        "en": "Awake mode ON: screen lock off. Amphetamine is not installed – with the lid closed the "
                              "Mac sleeps; on power caffeinate keeps it awake while a continuation is pending or "
                              "night mode is on."},
    "wm_aus": {"de": "Wach-Modus AUS: Bildschirmsperre wieder aktiv ({sperre}).",
               "en": "Awake mode OFF: screen lock active again ({sperre})."},
    "wm_uebernommen": {"de": "Gesicherte Sperrzeit aus dem alten Remote-Skript übernommen ({wert}).",
                       "en": "Saved lock delay taken over from the old remote script ({wert})."},
    "wm_log": {"de": "Wach-Modus: {text}", "en": "awake mode: {text}"},
    "wm_aktion": {"de": "Unbekannte Aktion „{aktion}“ – möglich: an, aus, status",
                  "en": "Unknown action \"{aktion}\" – possible: on, off, status"},
    "wm_hilfe": {"de": "Wach-Modus: Mac wach halten, Bildschirmsperre aus (an|aus|status)",
                 "en": "awake mode: keep the Mac awake, screen lock off (on|off|status)"},
    "wm_meta_aktion": {"de": "an|aus|status", "en": "on|off|status"},
    "wm_st_zeile": {"de": "{text} · Bildschirmsperre: {sperre} · Amphetamine: {amph}",
                    "en": "{text} · screen lock: {sperre} · Amphetamine: {amph}"},
    "wm_sperre_off": {"de": "aus", "en": "off"},
    "wm_sperre_sofort": {"de": "sofort", "en": "immediate"},
    "wm_amph_fehlt": {"de": "nicht installiert", "en": "not installed"},
    "wm_amph_bereit": {"de": "bereit", "en": "ready"},
    "wm_amph_verweigert": {"de": "Automation nicht erlaubt", "en": "automation not allowed"},
    "wm_amph_ungeprueft": {"de": "noch nicht geprüft", "en": "not checked yet"},
    "wm_art_amphetamine": {"de": "Amphetamine", "en": "Amphetamine"},
    "wm_art_caffeinate": {"de": "caffeinate, nur am Netzteil", "en": "caffeinate, on power only"},
    "wm_art_aus": {"de": "aus", "en": "off"},
    "wm_zu_ok": {"de": ", zugeklappt ok", "en": ", lid closed ok"},
    "wm_zu_nein": {"de": ", zugeklappt schläft er", "en": ", sleeps with the lid closed"},
    "wm_text_aus": {"de": "Wach-Modus aus", "en": "Awake mode off"},
    "wm_text_manuell": {"de": "Wach-Modus an, Sperre aus ({art}{zu})", "en": "Awake mode on, screen lock off ({art}{zu})"},
    "wm_text_manuell_ohne": {"de": "Wach-Modus an, Sperre aus (ohne Amphetamine)",
                             "en": "Awake mode on, screen lock off (without Amphetamine)"},
    "wm_text_auto": {"de": "Wach bis {zeit} ({art}{zu})", "en": "Awake until {zeit} ({art}{zu})"},
    "wm_befehl": {"de": "{pfad} wach an", "en": "{pfad} awake on"},
    "wm_befehl_aus": {"de": "{pfad} wach aus", "en": "{pfad} awake off"},
    "wm_amph_start": {"de": "Amphetamine-Sitzung bis {zeit} gestartet", "en": "Amphetamine session started until {zeit}"},
    "wm_amph_dry": {"de": "würde eine Amphetamine-Sitzung bis {zeit} starten",
                    "en": "would start an Amphetamine session until {zeit}"},
    "wm_amph_ende": {"de": "eigene Amphetamine-Sitzung beendet", "en": "own Amphetamine session ended"},
    "wm_amph_ende_dry": {"de": "würde die eigene Amphetamine-Sitzung beenden",
                         "en": "would end the own Amphetamine session"},
    "wm_amph_fehler": {"de": "Amphetamine-Sitzung fehlgeschlagen ({fehler})", "en": "Amphetamine session failed ({fehler})"},
    "wm_push_automation": {"de": "Der Limit-Wächter darf Amphetamine nicht steuern. Erlauben unter Systemeinstellungen > "
                                 "Datenschutz & Sicherheit > Automation – bis dahin hält nur caffeinate den Mac wach "
                                 "(nur am Netzteil, zugeklappt schläft er).",
                           "en": "The watchdog is not allowed to control Amphetamine. Allow it in System Settings > "
                                 "Privacy & Security > Automation – until then only caffeinate keeps the Mac awake "
                                 "(on power only, it sleeps with the lid closed)."},
    "wm_rueckbau_modus_an": {"de": "ACHTUNG: Der Wach-Modus ist noch an, die Bildschirmsperre bleibt aus. Zuerst ausführen: {befehl}",
                             "en": "WARNING: awake mode is still on, the screen lock stays off. Run first: {befehl}"},
    "wm_kf_sperre": {"de": "wach.sperre_standard muss eine ganze Zahl von 0 bis 86400 sein",
                     "en": "wach.sperre_standard must be a whole number from 0 to 86400"},

    # ---- v1.4: App ----
    "app_uebersicht": {"de": "Übersicht", "en": "Overview"},
    "app_g_wartet": {"de": "{anzahl} Sitzung(en) warten", "en": "{anzahl} session(s) waiting"},
    "app_nacht_kachel": {"de": "Nacht", "en": "Night"},
    "app_wach_kachel": {"de": "Wach", "en": "Awake"},
    "app_pause_kachel": {"de": "Pause", "en": "Pause"},
    "app_an_bis": {"de": "an bis {zeit}", "en": "on until {zeit}"},
    "app_aus": {"de": "aus", "en": "off"},
    "app_bis": {"de": "bis {zeit}", "en": "until {zeit}"},
    "app_wach_auto": {"de": "automatisch", "en": "automatic"},
    "app_wach_auto_bis": {"de": "automatisch bis {zeit}", "en": "auto until {zeit}"},
    "app_wach_manuell": {"de": "an · Sperre aus", "en": "on · lock off"},
    "app_wach_dialog": {"de": "Passwort-Dialog …", "en": "Password dialog ..."},
    "app_wach_an_hilfe": {"de": "Mac wach halten und Bildschirmsperre ausschalten (fragt nach dem Passwort)",
                          "en": "Keep the Mac awake and turn the screen lock off (asks for your password)"},
    "app_wach_aus_hilfe": {"de": "Wach-Modus beenden und Bildschirmsperre wiederherstellen (fragt nach dem Passwort)",
                           "en": "End awake mode and restore the screen lock (asks for your password)"},
    "app_wach_fehler": {"de": "Wach-Modus: {fehler}", "en": "Awake mode: {fehler}"},
    "app_wf_passwort": {"de": "Passwort falsch oder abgelehnt", "en": "password wrong or rejected"},
    "app_wf_system": {"de": "Systemaufruf fehlgeschlagen", "en": "system call failed"},
    "app_pause_bis_fortsetzen": {"de": "Bis ich fortsetze", "en": "Until I resume"},
    "app_einstellungen": {"de": "Einstellungen", "en": "Settings"},
    "app_hinweise": {"de": "Hinweise", "en": "Notes"},
    "app_quelle_alter": {"de": "{quelle} · vor {dauer}", "en": "{quelle} · {dauer} ago"},
    "app_weitere": {"de": "+{n} weitere", "en": "+{n} more"},
    "app_weniger": {"de": "Weniger anzeigen", "en": "Show less"},
    "app_offiziell_zeile": {"de": "Offizielle Nutzungsanzeige: {zustand}", "en": "Official usage display: {zustand}"},
    "app_of_ok": {"de": "verbunden", "en": "connected"},
    "app_of_aus": {"de": "abgeschaltet", "en": "turned off"},
    "app_of_auth": {"de": "Anmeldung abgelehnt", "en": "sign-in rejected"},
    "app_of_rate": {"de": "zu viele Abrufe – später erneut", "en": "too many requests - retrying later"},
    "app_of_netz": {"de": "nicht erreichbar", "en": "not reachable"},
    "app_of_format": {"de": "unbekanntes Antwortformat", "en": "unknown response format"},
    "app_of_kein_token": {"de": "keine Anmeldung gefunden", "en": "no sign-in found"},
    "app_of_abgelaufen": {"de": "Anmeldung abgelaufen – Werte evtl. verzögert", "en": "sign-in expired – values may lag"},
    "app_of_fehler": {"de": "Fehler ({fehler})", "en": "error ({fehler})"},
    "app_sperre": {"de": "Bildschirmsperre: {wert}", "en": "Screen lock: {wert}"},
    "app_sperre_aus": {"de": "aus", "en": "off"},
    "app_sperre_sofort": {"de": "sofort", "en": "immediately"},
    "app_sperre_nach": {"de": "nach {dauer}", "en": "after {dauer}"},
    "app_netzteil": {"de": "Netzteil: {wert}", "en": "Power adapter: {wert}"},
    "app_zugeklappt": {"de": "Zugeklappt wach: {wert}", "en": "Awake with lid closed: {wert}"},
    "app_amphetamine": {"de": "Amphetamine: {wert}", "en": "Amphetamine: {wert}"},
    "app_amph_fehlt": {"de": "nicht installiert", "en": "not installed"},
    "app_amph_bereit": {"de": "bereit", "en": "ready"},
    "app_amph_verweigert": {"de": "keine Berechtigung (Systemeinstellungen › Datenschutz › Automation)",
                            "en": "not allowed (System Settings > Privacy > Automation)"},
    "app_amph_ungeprueft": {"de": "noch nicht geprüft", "en": "not checked yet"},
    "app_ja": {"de": "ja", "en": "yes"},
    "app_nein": {"de": "nein", "en": "no"},
    # --- App: Kontext je Sitzung (Detailansicht, Mini-Balken, Schwellen) ---
    # (app_kontext_tokens/_quelle_*/_warnung/_kritisch/_schwellen stehen im Kontext-Block weiter unten)
    "app_kontext_titel": {"de": "Kontext", "en": "Context"},
    "app_kontext_tokens_prozent": {"de": "{tokens} / {fenster} Tokens · {prozent}",
                           "en": "{tokens} / {fenster} tokens · {prozent}"},
    "app_kontext_keine": {"de": "Kontext: noch kein Messwert", "en": "Context: no reading yet"},
    "app_kontext_stufe_ok": {"de": "OK", "en": "OK"},
    "app_kontext_stufe_warnung": {"de": "WARNUNG", "en": "WARNING"},
    "app_kontext_stufe_kritisch": {"de": "KRITISCH", "en": "CRITICAL"},
    "app_kontext_modell": {"de": "Modell", "en": "Model"},
    "app_kontext_ort": {"de": "Ort", "en": "Location"},
    "app_kontext_zustand": {"de": "Zustand", "en": "State"},
    "app_kontext_aktivitaet": {"de": "Zuletzt aktiv", "en": "Last active"},
    "app_kontext_vor": {"de": "vor {dauer}", "en": "{dauer} ago"},
    "app_kontext_laufzeit": {"de": "Läuft seit", "en": "Running for"},
    "app_kontext_nacht": {"de": "Nachtmodus", "en": "Night mode"},
    "app_kontext_quelle": {"de": "Datenquelle", "en": "Data source"},
    "app_kontext_quelle_alter": {"de": "{quelle} · vor {dauer}", "en": "{quelle} · {dauer} ago"},
    "app_kontext_details": {"de": "Klicken für Details", "en": "Click for details"},
    "app_kontext_zuklappen": {"de": "Klicken zum Zuklappen", "en": "Click to collapse"},

    # ---- v1.4 Nativ zuerst, sanfter Stopp, Kontext-Tracking, Terminal-Zeile
    "kx_kf_stopp_art": {"de": "schwellen.claude_stopp_art muss \"sanft\" oder \"geordnet\" sein",
                        "en": "schwellen.claude_stopp_art must be \"sanft\" (soft) or \"geordnet\" (orderly)"},
    "kx_kf_reihenfolge": {"de": "kontext.warnung muss kleiner als kontext.kritisch sein",
                          "en": "kontext.warnung must be lower than kontext.kritisch"},
    "kx_kf_fenster": {"de": "kontext.standard_fenster muss eine ganze Zahl ab 1000 sein",
                      "en": "kontext.standard_fenster must be a whole number of at least 1000"},
    "kx_kf_ruht": {"de": "anzeige.ruht_stunden muss zwischen 0 und 168 liegen",
                   "en": "anzeige.ruht_stunden must be between 0 and 168"},
    "sanft_deny": {
        "de": "{app}: Limit nah ({stand}) – keine neuen Subagents/Workflows starten, selbst weiterarbeiten; "
              "laufende dürfen fertig werden.",
        "en": "{app}: limit close ({stand}) - do not start new subagents/workflows, keep working yourself; "
              "running ones may finish.",
    },
    "sanft_kontext": {
        "de": "Hinweis {app}: Nutzungslimit nah ({stand}). Keine neuen Subagents oder Workflows starten, selbst "
              "weiterarbeiten; laufende dürfen fertig werden. Am Limit übernimmt Claude selbst.",
        "en": "Note from {app}: usage limit close ({stand}). Do not start new subagents or workflows, keep working "
              "yourself; running ones may finish. At the limit Claude takes over by itself.",
    },
    "push_stopp_sanft": {
        "de": "{n}: Stopp-Schwelle erreicht ({art} {pct}). Keine neuen Subagents/Workflows; laufende Arbeit geht "
              "weiter, am Limit setzt Claude selbst fort. Reset {reset}.{hinweis}",
        "en": "{n}: stop threshold reached ({art} {pct}). No new subagents/workflows; running work goes on, at the "
              "limit Claude continues by itself. Resets {reset}.{hinweis}",
    },
    "kx_hinweis_sitzung": {
        "de": "Hinweis {app}: Kontext bei {pct} ({tokens} / {fenster}) – Übergabe/Kompaktierung vorbereiten.",
        "en": "Note from {app}: context at {pct} ({tokens} / {fenster}) - prepare a handoff or compaction.",
    },
    "kx_push_warnung": {
        "de": "{n}: Kontext der Sitzung {id} bei {pct} ({tokens} / {fenster}) – Übergabe oder Kompaktierung "
              "vorbereiten.",
        "en": "{n}: context of session {id} at {pct} ({tokens} / {fenster}) - prepare a handoff or compaction.",
    },
    "kx_push_kritisch": {
        "de": "{n}: Kontext der Sitzung {id} kritisch: {pct} ({tokens} / {fenster}) – jetzt übergeben oder "
              "kompaktieren.",
        "en": "{n}: context of session {id} critical: {pct} ({tokens} / {fenster}) - hand off or compact now.",
    },
    "sl_kontext": {"de": "ctx", "en": "ctx"},
    "sl_woche": {"de": "Wo", "en": "wk"},
    "st_nativ": {"de": " · Claude setzt nach Reset {zeit} selbst fort",
                 "en": " · Claude continues by itself after reset {zeit}"},
    "st_kontext": {"de": " · Kontext {pct}", "en": " · context {pct}"},
    "st_kontext_schwellen": {"de": "Kontext: Warnung {w} %, kritisch {k} %",
                             "en": "Context: warning {w}%, critical {k}%"},
    "fs_lage_nativ": {"de": "setzt {zeit} selbst fort", "en": "resumes at {zeit}"},
    "app_kontext": {"de": "Kontext", "en": "Context"},
    "app_kontext_leer": {"de": "–", "en": "–"},
    "app_kontext_tokens": {"de": "{tokens} / {fenster}", "en": "{tokens} / {fenster}"},
    "app_kontext_quelle_statusline": {"de": "Statusline", "en": "Status line"},
    "app_kontext_quelle_transcript": {"de": "Transcript", "en": "Transcript"},
    "app_kontext_quelle_rollout": {"de": "Codex-Protokoll", "en": "Codex log"},
    "app_kontext_ok": {"de": "Kontext ok", "en": "Context ok"},
    "app_kontext_warnung": {"de": "Kontext-Warnung", "en": "Context warning"},
    "app_kontext_kritisch": {"de": "Kontext kritisch", "en": "Context critical"},
    "app_kontext_schwellen": {"de": "Kontext-Schwellen", "en": "Context thresholds"},
    "app_kontext_warnung_schwelle": {"de": "Kontext: Warnung", "en": "Context: warning"},
    "app_kontext_kritisch_schwelle": {"de": "Kontext: kritisch", "en": "Context: critical"},
    "app_nativ": {"de": "Claude setzt selbst fort", "en": "Claude continues by itself"},
}
